{% set name = "magcluster" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9fadcf7869745b1999853f4002170802bab06240e5e7afb2da918c577e9f4de3

build:
  number: 0
  entry_points:
    - magcluster = magcluster:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - clinker-py
    - openpyxl
    - pandas
    - pip
    - python
  run:
    - blast =2.9
    - tbl2asn =25.7
    - prokka =1.13.4
    - clinker-py
    - openpyxl
    - pandas =1.3.1
    - python =3.7.10
    - pip

test:
  imports:
    - magcluster
  commands:
    - magcluster --help

about:
  home: "https://github.com/RunJiaJi/magcluster"
  license: "GPL-2.0-or-later"
  license_family: GPL2
  license_file: 
  summary: "Magnetosome gene cluster annotation, screening and mapping tool"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - Runjiaji
